export const endpoints = {
  auth: {
    login: "/auth/admin/login",
    logout: "/auth/admin/logout",
    me: "/auth/admin/me",
    csrf: "/auth/csrf",
  },
  team: {
    list: "/team",
    detail: (slug: string) => `/team/${slug}`,
    adminList: "/admin/team",
    create: "/admin/team",
    update: (id: string) => `/admin/team/${id}`,
    delete: (id: string) => `/admin/team/${id}`,
    reorder: "/admin/team/reorder",
  },
  services: {
    list: "/services",
    detail: (slug: string) => `/services/${slug}`,
    adminList: "/admin/services",
    create: "/admin/services",
    update: (id: string) => `/admin/services/${id}`,
    delete: (id: string) => `/admin/services/${id}`,
  },
  articles: {
    list: "/articles",
    detail: (slug: string) => `/articles/${slug}`,
    categories: "/articles/categories",
    adminList: "/admin/articles",
    create: "/admin/articles",
    update: (id: string) => `/admin/articles/${id}`,
    delete: (id: string) => `/admin/articles/${id}`,
    createCategory: "/admin/article-categories",
    updateCategory: (id: string) => `/admin/article-categories/${id}`,
    deleteCategory: (id: string) => `/admin/article-categories/${id}`,
  },
  reviews: {
    list: "/reviews",
    submit: "/reviews",
    adminList: "/admin/reviews",
    update: (id: string) => `/admin/reviews/${id}`,
    approve: (id: string) => `/admin/reviews/${id}/approve`,  // PATCH
    delete: (id: string) => `/admin/reviews/${id}`,
  },
  career: {
    list: "/career",
    detail: (slug: string) => `/career/${slug}`,
    apply: (id: string) => `/career/${id}/apply`,
    adminList: "/admin/career",
    create: "/admin/career",
    update: (id: string) => `/admin/career/${id}`,
    delete: (id: string) => `/admin/career/${id}`,
    applications: "/admin/career/applications",
    updateApplicationStatus: (appId: string) => `/admin/career/applications/${appId}/status`,
  },
  analytics: {
    pageview: "/analytics/pageview",
    overview: "/admin/analytics/overview",
    formSubmissions: "/admin/analytics/forms",
  },
  faq: {
    list: "/faq",
    adminList: "/admin/faq",
    create: "/admin/faq",
    update: (id: string) => `/admin/faq/${id}`,
    delete: (id: string) => `/admin/faq/${id}`,
  },
  seo: {
    byPage: (slug: string) => `/seo/pages/${slug}`,
    adminAll: "/admin/seo",
    adminByPage: (slug: string) => `/admin/seo/${slug}`,
    adminUpdate: (slug: string) => `/admin/seo/${slug}`,
  },
  cms: {
    pageSections: (slug: string) => `/cms/pages/${slug}`,
    settings: "/cms/settings",
    navigation: "/cms/settings/navigation",
    adminPageSections: (slug: string) => `/admin/cms/pages/${slug}`,
    adminUpdateSection: (sectionId: string) => `/admin/cms/sections/${sectionId}`,
    adminToggleSection: (sectionId: string) => `/admin/cms/sections/${sectionId}/toggle`,
    adminReorderSections: (slug: string) => `/admin/cms/pages/${slug}/reorder`,
    adminSectionVersions: (sectionId: string) => `/admin/cms/sections/${sectionId}/versions`,
    adminUpdateSettings: "/admin/cms/settings",
    adminUpdateNavigation: "/admin/cms/settings/navigation",
  },
  contact: {
    submit: "/contact",
  },
};
