services:
  web:
    container_name: mrp-law-fe
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API: ${NEXT_PUBLIC_API}
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
        NEXT_PUBLIC_KEY: ${NEXT_PUBLIC_KEY}
    env_file:
      - .env.local
    ports:
      - "127.0.0.1:3003:3000"
    restart: unless-stopped
    networks:
      - mrp-law-network

networks:
  mrp-law-network:
    external: true
