"use client";

import { PageSchemaEditor, type SectionSchema } from "./PageSchemaEditor";

const SCHEMAS: SectionSchema[] = [
  {
    key: "hero",
    label: "Hero Section",
    description: "Banner utama halaman About",
    fields: [
      { type: "divider", label: "Gambar Hero" },
      { key: "image_url", label: "Gambar Hero", type: "image", folder: "pages" },
      { type: "divider", label: "Badge" },
      { key: "badge_id", label: "Badge (Indonesia)", type: "text" },
      { key: "badge_en", label: "Badge (English)", type: "text" },
      { type: "divider", label: "Heading" },
      { key: "heading_id", label: "Heading (Indonesia)", type: "text", span: "full" },
      { key: "heading_en", label: "Heading (English)", type: "text", span: "full" },
      { type: "divider", label: "Intro" },
      { key: "intro_id", label: "Intro (Indonesia)", type: "textarea", span: "full" },
      { key: "intro_en", label: "Intro (English)", type: "textarea", span: "full" },
    ],
  },
  {
    key: "story",
    label: "Cerita Kantor",
    description: "Sejarah dan paragraf cerita perjalanan kantor",
    fields: [
      { type: "divider", label: "Subheading & Judul" },
      { key: "story_heading_id", label: "Subheading (Indonesia)", type: "text" },
      { key: "story_heading_en", label: "Subheading (English)", type: "text" },
      { key: "story_title_id", label: "Judul Section (Indonesia)", type: "text", span: "full" },
      { key: "story_title_en", label: "Section Title (English)", type: "text", span: "full" },
      { type: "divider", label: "Paragraf" },
      { key: "story_p1_id", label: "Paragraf 1 (Indonesia)", type: "textarea", span: "full" },
      { key: "story_p1_en", label: "Paragraph 1 (English)", type: "textarea", span: "full" },
      { key: "story_p2_id", label: "Paragraf 2 (Indonesia)", type: "textarea", span: "full" },
      { key: "story_p2_en", label: "Paragraph 2 (English)", type: "textarea", span: "full" },
      { key: "story_p3_id", label: "Paragraf 3 (Indonesia)", type: "textarea", span: "full" },
      { key: "story_p3_en", label: "Paragraph 3 (English)", type: "textarea", span: "full" },
      { type: "divider", label: "Tombol CTA Tim" },
      { key: "team_cta_id", label: "Label Tombol (Indonesia)", type: "text" },
      { key: "team_cta_en", label: "Button Label (English)", type: "text" },
    ],
  },
  {
    key: "stats",
    label: "Statistik",
    description: "4 angka statistik pencapaian kantor",
    fields: [
      { type: "divider", label: "Nilai Statistik" },
      { key: "stat_founded_value", label: "Tahun Berdiri (angka)", type: "text" },
      { key: "stat_years_value", label: "Tahun Pengalaman (angka)", type: "text" },
      { key: "stat_cases_value", label: "Jumlah Kasus (angka)", type: "text" },
      { key: "stat_clients_value", label: "Jumlah Klien (angka)", type: "text" },
      { type: "divider", label: "Label Statistik" },
      { key: "stat_founded_id", label: "Label Tahun Berdiri (Indonesia)", type: "text" },
      { key: "stat_founded_en", label: "Founded Label (English)", type: "text" },
      { key: "stat_years_id", label: "Label Pengalaman (Indonesia)", type: "text" },
      { key: "stat_years_en", label: "Experience Label (English)", type: "text" },
      { key: "stat_cases_id", label: "Label Kasus (Indonesia)", type: "text" },
      { key: "stat_cases_en", label: "Cases Label (English)", type: "text" },
      { key: "stat_clients_id", label: "Label Klien (Indonesia)", type: "text" },
      { key: "stat_clients_en", label: "Clients Label (English)", type: "text" },
    ],
  },
  {
    key: "vision_mission",
    label: "Visi & Misi",
    description: "Pernyataan visi dan misi kantor",
    fields: [
      { type: "divider", label: "Visi" },
      { key: "vision_heading_id", label: "Judul Visi (Indonesia)", type: "text" },
      { key: "vision_heading_en", label: "Vision Heading (English)", type: "text" },
      { key: "vision_text_id", label: "Teks Visi (Indonesia)", type: "textarea", span: "full" },
      { key: "vision_text_en", label: "Vision Text (English)", type: "textarea", span: "full" },
      { type: "divider", label: "Misi" },
      { key: "mission_heading_id", label: "Judul Misi (Indonesia)", type: "text" },
      { key: "mission_heading_en", label: "Mission Heading (English)", type: "text" },
      { key: "mission_text_id", label: "Teks Misi (Indonesia)", type: "textarea", span: "full" },
      { key: "mission_text_en", label: "Mission Text (English)", type: "textarea", span: "full" },
    ],
  },
  {
    key: "values",
    label: "Nilai-Nilai Perusahaan",
    description: "4 nilai inti (integrity, collaboration, innovation, commitment)",
    fields: [
      { type: "divider", label: "Header Section" },
      { key: "values_heading_id", label: "Subheading (Indonesia)", type: "text" },
      { key: "values_heading_en", label: "Subheading (English)", type: "text" },
      { key: "values_title_id", label: "Judul Section (Indonesia)", type: "text", span: "full" },
      { key: "values_title_en", label: "Section Title (English)", type: "text", span: "full" },
      { type: "divider", label: "Integritas" },
      { key: "integrity_id", label: "Label (Indonesia)", type: "text" },
      { key: "integrity_en", label: "Label (English)", type: "text" },
      { key: "integrity_desc_id", label: "Deskripsi (Indonesia)", type: "textarea", span: "full" },
      { key: "integrity_desc_en", label: "Description (English)", type: "textarea", span: "full" },
      { type: "divider", label: "Kolaborasi" },
      { key: "collaboration_id", label: "Label (Indonesia)", type: "text" },
      { key: "collaboration_en", label: "Label (English)", type: "text" },
      { key: "collaboration_desc_id", label: "Deskripsi (Indonesia)", type: "textarea", span: "full" },
      { key: "collaboration_desc_en", label: "Description (English)", type: "textarea", span: "full" },
      { type: "divider", label: "Inovasi" },
      { key: "innovation_id", label: "Label (Indonesia)", type: "text" },
      { key: "innovation_en", label: "Label (English)", type: "text" },
      { key: "innovation_desc_id", label: "Deskripsi (Indonesia)", type: "textarea", span: "full" },
      { key: "innovation_desc_en", label: "Description (English)", type: "textarea", span: "full" },
      { type: "divider", label: "Komitmen" },
      { key: "commitment_id", label: "Label (Indonesia)", type: "text" },
      { key: "commitment_en", label: "Label (English)", type: "text" },
      { key: "commitment_desc_id", label: "Deskripsi (Indonesia)", type: "textarea", span: "full" },
      { key: "commitment_desc_en", label: "Description (English)", type: "textarea", span: "full" },
    ],
  },
  {
    key: "cta",
    label: "CTA Konsultasi",
    description: "Section ajakan konsultasi di bawah halaman About",
    fields: [
      { key: "cta_heading_id", label: "Heading (Indonesia)", type: "text", span: "full" },
      { key: "cta_heading_en", label: "Heading (English)", type: "text", span: "full" },
      { key: "cta_sub_id", label: "Subheading (Indonesia)", type: "textarea", span: "full" },
      { key: "cta_sub_en", label: "Subheading (English)", type: "textarea", span: "full" },
      { key: "cta_btn_id", label: "Label Tombol (Indonesia)", type: "text" },
      { key: "cta_btn_en", label: "Button Label (English)", type: "text" },
    ],
  },
];

export function AboutPageEditor() {
  return <PageSchemaEditor pageSlug="about" schemas={SCHEMAS} />;
}
